apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::584455519448:role/ssm-for-eks
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  serviceAccountName: cart
  containers:
    - name: cart
      image: 584455519448.dkr.ecr.us-east-1.amazonaws.com/cart:2.0.0
  initContainers:
    - name: aws-ssm-param-store
      image: 584455519448.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store:2.0.0
      args: ["sample:dev.docdb.pass"]


#args will fetch aws parameters
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

